server:
  port: 8082


spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
      - id: "backend"
        predicates:
        - Path=/backend/**
      - filters:
        - StripPrefix=1
        uri: lb://BACKEND
      - id: "backend"
        predicates:
        - Path=/frontend/**
      - filters:
        - StripPrefix=1
        uri: lb://FRONTEND
  profiles:
  - gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
